module.exports = {
  products: [
    {
      _id: '1',
      name: 'РЮКЗАК ДЛЯ АЛЬПИНИЗМА 70 ЛИТРОВ – MAKALU 45/70',
      category: 'backpack',
      image: '/src/images/product-1.jpg',
      color: "red",
      price: 7999,
      brand: 'SIMOND',
      rating: 4,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'РЮКЗАК 70 Л TRAVEL 500',
      category: 'backpack',
      image: '/src/images/product-2.jpg',
      color: "grey",
      price: 6499,
      brand: 'FORCLAZ',
      rating: 4,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'РЮКЗАК ТУРИСТИЧЕСКИЙ 60 Л',
      category: 'backpack',
      image: '/src/images/product-3.jpg',
      color: "blue",
      price: 3799,
      brand: 'FORCLAZ',
      rating: 4.5,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'РЮКЗАК ДЛЯ ГОРНОГО ТРЕККИНГА FORCLAZ 90 Л',
      category: 'backpack',
      image: '/src/images/product-4.jpg',
      color: "grey",
      brand: 'FORCLAZ',
      price: 4999,
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'СУМКА ДЛЯ ТРЕКИНГА - EXTEND ОТ 80 ДО 120 Л',
      category: 'bag',
      image: '/src/images/product-5.jpg',
      color: "yellow",
      price: 4499,
      brand: 'FORCLAZ',
      rating: 4.5,
      numReviews: 89,
      countInStock: 6,

    },
    {
      _id: '6',
      name: 'Сумка-баул Base Camp Duffel M Tnf Red/Tnf Black',
      category: 'bag',
      image: '/src/images/product-9.jpg',
      price: 9920,
      brand: 'The North Face',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
    },
    {
      _id: '7',
      name: 'СУМКА ДЛЯ ТРЕККИНГА DUFFEL 500 EXTEND 40–60 Л',
      category: 'bag',
      image: '/src/images/product-7.jpg',
      color: "blue",
      price: 3499,
      brand: 'FORCLAZ',
      rating: 4.4,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '8',
      name: 'Рюкзак Deuter Speed Lite 24 Chili-Lava',
      category: 'backpack',
      image: '/src/images/product-8.jpg',
      color: "red",
      price: 8790,
      brand: 'Deuter',
      rating: 5,
      numReviews: 2,
      countInStock: 6,
    },
    {
      _id: '9',
      name: 'РЮКЗАК СВЕРХЛЕГКИЙ 14+5 Л FAST HIKING FH900',
      category: 'backpack',
      image: '/src/images/product-6.jpg',
      color: "blue",
      price: 4699,
      brand: 'QUECHUA',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
    {
      _id: '10',
      name: 'Рюкзак Waldfuchs Cardinal-Maron',
      category: 'backpack',
      image: '/src/images/product-10.jpg',
      color: "pink",
      price: 3290,
      brand: 'Deuter',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
    },
  ],
};